name: test

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        ruby-version:
          - '2.3'
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - ruby-head

    steps:
      - run: sudo apt-get install -y tidy tcl tk

      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        continue-on-error: ${{ matrix.ruby-version == 'ruby-head' }}

      - run: bundle exec rake
        continue-on-error: ${{ matrix.ruby-version == 'ruby-head' }}
